# docker-compose dev
version: "3.1"
services:
  angular:
    container_name: ecf-arcadia-front
    ports:
      - 4200:80
    build: 
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./dist/ecf-arcadia-front:/usr/local/apache2/htdocs
